const express=require("express")
const userRouter=express.Router();
const userController=require("../controllers/user.controller")
const upload=require("../middleware/uploadImages")
const checkAuth=require("../middleware/checkAuth")
const checkRole=require("../middleware/checkRole")
userRouter.get("/", userController.getAllUser)
userRouter.post("/register", upload.single("avatar"), userController.register)
userRouter.post("/login",  userController.login)
userRouter.put("/changestatus/:id", userController.changeStatus)
userRouter.delete("/:id", checkAuth, checkRole, userController.deleteUser)
userRouter.get("/forgotpassword", userController.showForgotPassword)
userRouter.post("/forgotpassword", userController.forgotPassword)
userRouter.get("/resetpassword", userController.showResetPassword)
userRouter.post("/resetpassword", userController.resetPassword)
userRouter.get("/:id/address", checkAuth,userController.getInforUser)
userRouter.post("/:id/address",checkAuth, userController.createAddress)
userRouter.delete("/:idUser/address/:idAddress",checkAuth, userController.deleteAddress)
userRouter.put("/:idUser/address/:idAddress",checkAuth, userController.updateAddress)
module.exports=userRouter   